export const CLIENT_CREATED = 'CLIENT_CREATED';
export const REPAIR_CREATED = 'REPAIR_CREATED';
export const REPAIR_STATUS_CHANGED = 'REPAIR_STATUS_CHANGED';
export const BUDGET_CREATED = 'BUDGET_CREATED';
export const BUDGET_APPROVED = 'BUDGET_APPROVED';
export const BUDGET_REJECTED = 'BUDGET_REJECTED';
export const PRINT_ORDER_CREATED = 'PRINT_ORDER_CREATED';
export const PRINT_ORDER_STATUS_CHANGED = 'PRINT_ORDER_STATUS_CHANGED';
