-- Migration: Create interview_sessions table for Interview V2 persistence
-- Description: Stores interview session state and schema in Supabase.
-- The SupabaseSessionStore uses this table as its backing store,
-- allowing interview sessions to survive worker restarts and scale horizontally.

-- +------------------+------------------------------------------------------+
-- | Column           | Description                                          |
-- +------------------+------------------------------------------------------+
-- | id               | UUID primary key, generated by the application       |
-- | schema_id        | Identifies which interview schema is being executed   |
-- | user_id          | NULLABLE — reserved for future frontend auth         |
-- | status           | One of: active, completed, expired                   |
-- | state            | Full interview state as JSONB (answers, history...)  |
-- | schema           | The interview schema snapshot as JSONB               |
-- | created_at       | Auto-set on insert                                   |
-- | updated_at       | Auto-updated on every row modification               |
-- +------------------+------------------------------------------------------+

CREATE TABLE IF NOT EXISTS interview_sessions (
  id         UUID PRIMARY KEY,
  schema_id  TEXT NOT NULL,
  user_id    UUID NULL,
  status     TEXT NOT NULL DEFAULT 'active'
             CHECK (status IN ('active', 'completed', 'expired')),
  state      JSONB NOT NULL,
  schema     JSONB NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Index for lookups by schema_id (admin queries, analytics)
CREATE INDEX IF NOT EXISTS idx_interview_sessions_schema_id
  ON interview_sessions (schema_id);

-- Index for filtering by status (active vs completed)
CREATE INDEX IF NOT EXISTS idx_interview_sessions_status
  ON interview_sessions (status);

-- Index for sorting by creation date (listing recent sessions)
CREATE INDEX IF NOT EXISTS idx_interview_sessions_created_at
  ON interview_sessions (created_at DESC);

-- Index for user-scoped queries (future use)
CREATE INDEX IF NOT EXISTS idx_interview_sessions_user_id
  ON interview_sessions (user_id)
  WHERE user_id IS NOT NULL;

-- Trigger to auto-update updated_at on row modification
CREATE OR REPLACE FUNCTION update_interview_sessions_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_interview_sessions_updated_at ON interview_sessions;
CREATE TRIGGER trg_interview_sessions_updated_at
  BEFORE UPDATE ON interview_sessions
  FOR EACH ROW
  EXECUTE FUNCTION update_interview_sessions_updated_at();

-- ── Row Level Security ─────────────────────────────────────────
-- Design principles:
--   1. The backend Worker uses the service_role key, which
--      automatically bypasses RLS. All store operations work
--      as-is without any policy changes.
--   2. Anonymous / unauthenticated requests are blocked at the
--      database level for all operations (SELECT, INSERT, UPDATE,
--      DELETE).
--   3. When frontend authentication is added, policies will be
--      extended to check user_id = auth.uid() so that users can
--      only access their own sessions.

ALTER TABLE interview_sessions ENABLE ROW LEVEL SECURITY;

-- Block anonymous SELECT
CREATE POLICY "service_role_all_select"
  ON interview_sessions
  FOR SELECT
  USING (auth.role() = 'service_role');

-- Block anonymous INSERT
CREATE POLICY "service_role_all_insert"
  ON interview_sessions
  FOR INSERT
  WITH CHECK (auth.role() = 'service_role');

-- Block anonymous UPDATE
CREATE POLICY "service_role_all_update"
  ON interview_sessions
  FOR UPDATE
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');

-- Block anonymous DELETE
CREATE POLICY "service_role_all_delete"
  ON interview_sessions
  FOR DELETE
  USING (auth.role() = 'service_role');
